name: Build & Lint

# Only trigger the event on pull-requests
on: [pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    # Test the latest release of Go
    strategy:
      matrix:
        go: [ '1.14', '1.13' ]
    steps:
      # Setup the workflow to use the specific version of Go
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
        id: go
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v2
      # Verify downloaded dependencies
      - name: Verify dependencies
        run: |
          go mod verify
          go mod download
          LINT_VERSION=1.26.0
          curl -fsSL https://github.com/golangci/golangci-lint/releases/download/v${LINT_VERSION}/golangci-lint-${LINT_VERSION}-linux-amd64.tar.gz | \
            tar xz --strip-components 1 --wildcards \*/golangci-lint
          mkdir -p bin && mv golangci-lint bin/
      # Run tests and generates a coverage profile
      - name: Test
        run: |
          go test -v -coverprofile=profile.cov ./...
      # Run Go benchmarks
      - name: Benchmark
        run: |
          go test -bench=. -benchmem
      # Sends code coverage report to Coveralls
      - name: Coveralls
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          GO111MODULE=off go get github.com/mattn/goveralls
          $(go env GOPATH)/bin/goveralls -coverprofile=profile.cov -service=github
